export enum ParamsEnum {
  STATICINFO_ID = "staticinfo_id",
  USERS_ID = "users_id",
  CATEGORY_ID = "category_id",
  CUSTOMERS_ID = "customers_id",
  SHIPPINGFEES_ID = "shippingfees_id",
  STUDENT_ID = "student_id",
  COURSE_ID = "course_id",
  EDUCATION_CLASS_ID = "edu_class_id",
  SUBJECT_ID = "subject_id",
  CURRICULUM_ID = "curriculum_id",
  GRADE_ID = "grade_id",
  BRANCH_ID = "branch_id",
  CYCLE_ID = "cycle_id",
  UNIT_ID = "unit_id",
  LESSON_ID = "lesson_id",
  QUESTION_ID = "question_id",
  CHILDREN_QUESTION_ID = "children_question_id",
  RE_SELLER_ID = "reseller_id",
  ROLE_ID = "role_id",
  CITY_ID = "city_id",
  Collection_ID = "collection_id",
  Manager_ID = "manager_id",
  REPORT_ID = "report_id",
  // RESELLER_ID = "reseller_id",
}
